name: Build Scratch Org

on: 
  workflow_dispatch:

jobs:
  CreateOrg:
    runs-on: ubuntu-latest
    container:
      image: jfgarcia268/sfdx_vlocity_java:latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login DevHub
      run: |
        echo ${{ secrets.SFDX_URL_DEVHUB }}   > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a DEVHUB -f env.sfdx
    - name: Create Org
      run: |
        sfdx force:org:create --definitionfile config/project-scratch-def.json -a ALIAS --durationdays 29 --targetdevhubusername DEVHUB
        sfdx force:user:password:generate --targetusername ALIAS --targetdevhubusername DEVHUB
        if [ -f org.info ]; then
          rm org.info  
        fi
        sfdx force:org:display --verbose --targetusername ALIAS  --verbose >> org.info
        sed '/.*─.*/d' org.info > tmpfile
        mv tmpfile org.info  
    - name: Upload Scratch Org Info
      uses: actions/upload-artifact@v2
      with:
        name: ScratchOrgInfo_$RANDOM
        path: org.info
    - name: Deploy Manage Package from sfdx-project.json
      run: |
        PACKAGE_ID=$(jq -r '.packageAliases."Vlocity CMT"' sfdx-project.json)
        echo "$PACKAGE_ID"
        sfdx force:package:install -p ${PACKAGE_ID} --targetusername ALIAS -w 1000 --noprompt
    - name: Deploy and Setup Salesforce
      run: |
        sfdx force:source:deploy --sourcepath force-app --targetusername ALIAS --verbose
        sfdx force:data:tree:import --targetusername ALIAS --plan sfdx-data/Account-plan.json
        sfdx force:user:permset:assign --targetusername ALIAS --permsetname HandsetBuy
    - name: Vlocity 1st Time Setup
      run: |
        vlocity -sfdx.username ALIAS --nojob packUpdateSettings 
        vlocity -sfdx.username ALIAS --nojob installVlocityInitial --verbose
        vlocity -sfdx.username ALIAS --nojob runApex -apex apex/cmt_InitializeOrg.cls
    - name: Vlocity Deploy
      run: |
        vlocity -sfdx.username ALIAS -job Deploy_Delta.yaml packDeploy --verbose true
        vlocity -sfdx.username ALIAS --nojob runApex -apex apex/RunProductBatchJobs.cls

